
service: serverless-ged

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-GED-user
  region: eu-west-3
  environment:
    bucketName: ${self:custom.bucketName}
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:*
          - s3:*
      Resource: '*'

plugins:
  - serverless-s3-sync
  - serverless-webpack


package:
  individually: true

custom:
  bucketName: lamarl-serverless-project-file-upload-2020
  tableName: serverless-GED-files
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist

functions:
  documents:
    handler: lambdas/endpoints/documents.handler
    events:
      # Post a new signed url
      - http:
            path: documents
            method: POST
            cors: true
      # Get a specific signed url
      - http:
            path: documents/{uuid}
            method: GET
            cors: true
      # Get all generated signed urls
      - http:
            path: documents/
            method: GET
            cors: true

resources:
  Resources:
    FileGEDBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST